import { expect, test } from '@playwright/test'
import { expectOnlyLoopbackRequests, installExportArtifactFixture, installLoopbackFixture } from './fixtures/loopback-api'

test('sanitized loopback fixture covers QR login UI', async ({ page }) => {
  await installLoopbackFixture(page)
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'WeChat login' })).toBeVisible()
  await page.getByRole('button', { name: 'Start QR login' }).click()
  await expect(page.getByRole('img', { name: 'QR-code login' })).toBeVisible()
  await page.getByRole('button', { name: 'Poll login status' }).click()
  await expect(page.getByText('Scanned', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Complete login' }).click()
  await expect(page.getByText('Authenticated', { exact: true })).toBeVisible()
  await expectOnlyLoopbackRequests(page)
})

test('sanitized account and article selections remain browser-local', async ({ page }) => {
  await installLoopbackFixture(page)
  await page.goto('/accounts')
  await page.getByRole('checkbox', { name: 'Select account-fixture' }).check()
  await expect(page.getByText('1 selected', { exact: false })).toBeVisible()
  await page.goto('/articles')
  await page.getByRole('checkbox', { name: 'Select Sanitized article one' }).check()
  await expect(page.getByText('1 selected', { exact: false })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search articles' }).fill('Sanitized')
  await expect(page.getByRole('cell', { name: 'Sanitized article one', exact: true })).toBeVisible()
  await expectOnlyLoopbackRequests(page)
})

test('saved queries are created, updated, and deleted with scoped confirmation', async ({ page }) => {
  const fixture = await installLoopbackFixture(page)
  await page.goto('/saved-queries')
  await page.getByRole('textbox', { name: 'Query name' }).fill('fixture recent')
  await page.getByRole('textbox', { name: 'Query JSON' }).fill('{"keyword":"fixture"}')
  await page.getByRole('button', { name: 'Save query' }).click()
  await expect(page.getByText('Saved query “fixture recent”.')).toBeVisible()
  await expect(page.getByRole('cell', { name: 'fixture recent', exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Select fixture recent' }).check()
  await page.getByRole('button', { name: 'Load selected query' }).click()
  await page.getByRole('textbox', { name: 'Query JSON' }).fill('{"keyword":"updated"}')
  await page.getByRole('button', { name: 'Save query' }).click()
  await expect(page.getByRole('button', { name: 'Load selected query' })).toBeEnabled()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Delete selected query' }).click()
  await expect(page.getByText('Deleted saved query “fixture recent”.')).toBeVisible()
  expect(fixture.requests.filter((request) => request.includes('/api/v1/saved-queries')).length).toBeGreaterThanOrEqual(4)
  await expectOnlyLoopbackRequests(page)
})

test('sanitized job observation and control use scoped local API calls', async ({ page }) => {
  const fixture = await installLoopbackFixture(page)
  await page.goto('/jobs')
  await expect(page.getByText('Running', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Select job-fixture-1' }).check()
  await expect(page.getByRole('heading', { name: 'Task detail' })).toBeVisible()
  await expect(page.getByText('Sanitized local progress', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Refresh detail' }).click()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Pause selected task' }).click()
  await expect.poll(() => fixture.controls.length).toBe(1)
  expect(fixture.controls[0]).toBe('/api/v1/jobs/job-fixture-1/pause')
  await expectOnlyLoopbackRequests(page)
})

test('sanitized export flow authorizes a directory, downloads an artifact, opens output, and verifies output', async ({ page }) => {
  const fixture = await installLoopbackFixture(page)
  await installExportArtifactFixture(page)
  await page.goto('/exports')
  await page.getByRole('button', { name: 'Authorize default directory' }).click()
  await expect(page.getByText('Authorized directory: Sanitized exports')).toBeVisible()
  await page.getByRole('heading', { name: '2. Select articles and format' }).scrollIntoViewIfNeeded()
  const articleIDs = page.getByRole('textbox', { name: 'Article IDs' })
  await articleIDs.evaluate((element) => {
    const textarea = element as HTMLTextAreaElement
    const setValue = Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype, 'value')?.set
    if (!setValue) throw new Error('textarea value setter is unavailable')
    setValue.call(textarea, 'article-fixture-1')
    textarea.dispatchEvent(new InputEvent('input', { bubbles: true, data: 'article-fixture-1', inputType: 'insertText' }))
    textarea.dispatchEvent(new Event('change', { bubbles: true }))
  })
  await expect(articleIDs).toHaveValue('article-fixture-1')
  await expect(page.getByRole('button', { name: 'Queue export' })).toBeEnabled()
  await page.getByRole('button', { name: 'Queue export' }).click()
  await expect(page.getByText('Export queued. Job ID: job-export-fixture')).toBeVisible()
  expect(fixture.exports).toHaveLength(1)
  expect(fixture.exports[0]).toContain('dir-sanitized')
  const exportRecord = page.getByRole('checkbox', { name: 'Select export export-fixture-1' })
  await exportRecord.evaluate((element) => (element as HTMLInputElement).click())
  await expect(exportRecord).toBeChecked()
  await page.getByRole('button', { name: 'View manifest' }).click()
  await expect(page.getByText('sanitized-article.md')).toBeVisible()
  await page.getByRole('heading', { name: 'Artifact download and output folder' }).scrollIntoViewIfNeeded()
  const downloadLink = page.getByRole('link', { name: 'Download' })
  await expect(downloadLink).toHaveAttribute('href', '/api/v1/exports/export-fixture-1/artifact?artifactId=artifact-fixture-1')
  const download = await Promise.all([page.waitForEvent('download'), downloadLink.click()])
  expect(download[0].suggestedFilename()).toBe('sanitized-article.md')
  const openConfirmation = page.getByRole('textbox', { name: 'Confirmation value' })
  await openConfirmation.evaluate((element) => {
    const input = element as HTMLInputElement
    const setValue = Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value')?.set
    if (!setValue) throw new Error('input value setter is unavailable')
    setValue.call(input, 'open-export-output:export-fixture-1')
    input.dispatchEvent(new InputEvent('input', { bubbles: true, data: 'open-export-output:export-fixture-1', inputType: 'insertText' }))
    input.dispatchEvent(new Event('change', { bubbles: true }))
  })
  await expect(openConfirmation).toHaveValue('open-export-output:export-fixture-1')
  await expect(page.getByRole('button', { name: 'Open output folder' })).toBeEnabled()
  const openRequest = page.waitForRequest((request) => request.method() === 'POST' && request.url().endsWith('/api/v1/exports/export-fixture-1/open'))
  await page.getByRole('button', { name: 'Open output folder' }).click()
  await expect((await openRequest).postDataJSON()).toEqual({ confirm: 'open-export-output:export-fixture-1' })
  await expect(page.getByText('The selected export output folder was opened.')).toBeVisible()
  await page.getByRole('button', { name: 'Verify export' }).click()
  await expect(page.getByText('Valid: 1 output verified.')).toBeVisible()
  await expectOnlyLoopbackRequests(page)
})

test('sanitized settings and storage maintenance flows do not reveal secrets', async ({ page }) => {
  const fixture = await installLoopbackFixture(page)
  await page.goto('/settings')
  await expect(page.getByText('account-fixture', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Download concurrency' }).fill('3')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()
  expect(fixture.preferencePatches).toHaveLength(1)
  await page.getByRole('button', { name: 'Create backup' }).click()
  await expect(page.getByRole('textbox', { name: 'Backup ID' })).toHaveValue('backup-fixture')
  await page.getByRole('button', { name: 'Verify backup' }).click()
  await expect(page.getByText('Backup verification passed.')).toBeVisible()
  await page.getByRole('button', { name: 'Generate GC plan' }).click()
  await page.getByRole('textbox', { name: 'One-time exact confirmation' }).fill('apply-gc-fixture')
  await page.getByRole('button', { name: 'Apply this plan once' }).click()
  await expect(page.getByText('GC completed.')).toBeVisible()
  await expect(page.locator('body')).not.toContainText('real-cookie')
  await expectOnlyLoopbackRequests(page)
})

test('failure states remain usable with sanitized local errors', async ({ page }) => {
  await installLoopbackFixture(page)
  await page.route('**/api/v1/articles?**', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Sanitized fixture unavailable' } }) }))
  await page.goto('/articles')
  await expect(page.getByRole('alert')).toContainText('The local article API is not available yet.')
  await expect(page.getByRole('button', { name: 'Retry' })).toBeVisible()
  await expectOnlyLoopbackRequests(page)
})
