import { expect, test } from '@playwright/test'
import { expectOnlyLoopbackRequests, installLoopbackFixture } from './fixtures/loopback-api'

test('sanitized loopback fixture covers QR login UI', async ({ page }) => {
  await installLoopbackFixture(page)
  await page.goto('/login')
  await expect(page.getByRole('heading', { name: 'WeChat login' })).toBeVisible()
  await page.getByRole('button', { name: 'Start QR login' }).click()
  await expect(page.getByRole('img', { name: 'QR-code login' })).toBeVisible()
  await page.getByRole('button', { name: 'Poll login status' }).click()
  await expect(page.getByText('Scanned', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Complete login' }).click()
  await expect(page.getByText('Authenticated', { exact: true })).toBeVisible()
  await expectOnlyLoopbackRequests(page)
})

test('sanitized account and article selections remain browser-local', async ({ page }) => {
  await installLoopbackFixture(page)
  await page.goto('/accounts')
  await page.getByRole('checkbox', { name: 'Select account-fixture' }).check()
  await expect(page.getByText('1 selected', { exact: false })).toBeVisible()
  await page.goto('/articles')
  await page.getByRole('checkbox', { name: 'Select Sanitized article one' }).check()
  await expect(page.getByText('1 selected', { exact: false })).toBeVisible()
  await page.getByRole('textbox', { name: 'Search articles' }).fill('Sanitized')
  await expect(page.getByRole('cell', { name: 'Sanitized article one', exact: true })).toBeVisible()
  await expectOnlyLoopbackRequests(page)
})

test('sanitized job observation and control use scoped local API calls', async ({ page }) => {
  const fixture = await installLoopbackFixture(page)
  await page.goto('/jobs')
  await expect(page.getByText('Running', { exact: true })).toBeVisible()
  await page.getByRole('checkbox', { name: 'Select job-fixture-1' }).check()
  page.once('dialog', (dialog) => dialog.accept())
  await page.getByRole('button', { name: 'Pause selected task' }).click()
  await expect.poll(() => fixture.controls.length).toBe(1)
  expect(fixture.controls[0]).toBe('/api/v1/jobs/job-fixture-1/pause')
  await expectOnlyLoopbackRequests(page)
})

test('sanitized export flow authorizes a directory, queues, and verifies output', async ({ page }) => {
  const fixture = await installLoopbackFixture(page)
  await page.goto('/exports')
  await page.getByRole('button', { name: 'Authorize default directory' }).click()
  await expect(page.getByText('Authorized directory: Sanitized exports')).toBeVisible()
  await page.getByRole('textbox', { name: 'Article IDs' }).fill('article-fixture-1')
  await expect(page.getByRole('button', { name: 'Queue export' })).toBeEnabled()
  await page.getByRole('button', { name: 'Queue export' }).click()
  await expect(page.getByText('Export queued. Job ID: job-export-fixture')).toBeVisible()
  expect(fixture.exports).toHaveLength(1)
  expect(fixture.exports[0]).toContain('dir-sanitized')
  await page.getByRole('checkbox', { name: 'Select export export-fixture-1' }).check()
  await page.getByRole('button', { name: 'View manifest' }).click()
  await expect(page.getByText('sanitized-article.md')).toBeVisible()
  await page.getByRole('button', { name: 'Verify export' }).click()
  await expect(page.getByText('Valid: 1 output verified.')).toBeVisible()
  await expectOnlyLoopbackRequests(page)
})

test('sanitized settings and storage maintenance flows do not reveal secrets', async ({ page }) => {
  const fixture = await installLoopbackFixture(page)
  await page.goto('/settings')
  await expect(page.getByText('account-fixture', { exact: true })).toBeVisible()
  await page.getByRole('textbox', { name: 'Download concurrency' }).fill('3')
  await page.getByRole('button', { name: 'Save preferences' }).click()
  await expect(page.getByText('Preferences saved.')).toBeVisible()
  expect(fixture.preferencePatches).toHaveLength(1)
  await page.getByRole('button', { name: 'Create backup' }).click()
  await expect(page.getByRole('textbox', { name: 'Backup ID' })).toHaveValue('backup-fixture')
  await page.getByRole('button', { name: 'Verify backup' }).click()
  await expect(page.getByText('Backup verification passed.')).toBeVisible()
  await page.getByRole('button', { name: 'Generate GC plan' }).click()
  await page.getByRole('textbox', { name: 'One-time exact confirmation' }).fill('apply-gc-fixture')
  await page.getByRole('button', { name: 'Apply this plan once' }).click()
  await expect(page.getByText('GC completed.')).toBeVisible()
  await expect(page.locator('body')).not.toContainText('real-cookie')
  await expectOnlyLoopbackRequests(page)
})

test('failure states remain usable with sanitized local errors', async ({ page }) => {
  await installLoopbackFixture(page)
  await page.route('**/api/v1/articles?**', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: { message: 'Sanitized fixture unavailable' } }) }))
  await page.goto('/articles')
  await expect(page.getByRole('alert')).toContainText('The local article API is not available yet.')
  await expect(page.getByRole('button', { name: 'Retry' })).toBeVisible()
  await expectOnlyLoopbackRequests(page)
})
