/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/workspaceTheme.source.ts
 * Command: astryx theme build src/theme/workspaceTheme.source.ts --out src/styles/theme.css
 * Generated: 2026-07-23T16:47:05.315Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const wechatArticleWorkspaceTheme: DefinedTheme;
