/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/workspaceTheme.source.ts
 * Command: astryx theme build src/theme/workspaceTheme.source.ts --out src/styles/theme.css
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const wechatArticleWorkspaceTheme: DefinedTheme;
